### ISSUE TITLE
Offering help with testing machines

### ISSUE THREAD

**Issue by iLoveTux** [SpamixOfficial/OpenClick#10]
I'm coming here from your announcement at https://www.reddit.com/r/Python/comments/z9xqsc/prerelease_v03_of_openclick_just_released_for/.

In that announcement, you mentioned that you need support with testing on various operating systems I would be happy to help with my Windows, Fedora and Ubuntu testing machines. Once that is in place, I can help with a transition to a free (for open source) Continuous Integration service to automatically test on every commit.

The only thing I need to get started on this process is an automated test suite. This might sound intimidating, but we simply need some code which tests out your application code.

The Python's standard library `unittest` module would be a good place to start if you are not familiar with automated testing. The test suite would typically live in a directory named `test` which would be a peer to your main source code file or directory.

**Comment by SpamixOfficial** [comment]
@iLoveTux Hello!

Please contact me on Reddit (AlexDaBruh)!
