### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by skelly37** [SpamixOfficial/OpenClick#17]
You declare to have it working only under X11, how about adding support for Wayland? ;D

**Comment by SpamixOfficial** [comment]
Wayland support was added in the latest push to the dev branch! Official support is coming v0.5

**Comment by SpamixOfficial** [comment]
Wayland support was added in the latest push to the dev branch! Official support is coming v0.5

**Comment by SpamixOfficial** [comment]
@skelly37 Jokes on you, I just realized Wayland just told me to fuck off. Seriously though, I just realized OpenClick will only work with applications using XWayland. I'll look into making a Wayland edition that works better than the current state.
